spring.application.name=backend

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/forever}
spring.datasource.username=${DATABASE_USERNAME:alokgupta}
spring.datasource.password=${DATABASE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true